### ISSUE TITLE
The core doesn't look in the correct folder for the "aes_keys.txt"

### ISSUE THREAD

**Issue by bslenul** [libretro/citra2018#1]
See https://github.com/libretro/citra/issues/85#issuecomment-846877340 for more details.

Encrypted games work fine if the "aes_keys.txt" file is in standalone location (at least on Windows, haven't tried anything else), even if the "Savegame location" core option is set to "LibRetro Default". It doesn't load if you're using the RA saves folder however :(

**Comment by dverbeeck** [comment]
any updates on this? does not seem to work for me w/ lakka 3.1 or RetroArch 1.9.4 in Linux

Keys are in /storage/system/Citra/sysdata/

**Comment by FrostKnight** [comment]
I am curious as well, but hey, it least it works for my purposes! :)

I was able to compile it and load it.
Very few, if any errors.
